mandatoryAccounts:
  - name: Management
    description: Management account
    email: scottemalone@gmail.com
    organizationalUnit: Root

  - name: LogArchive
    description: Central log archive account
    email: logemalone@gmail.com
    organizationalUnit: Security

  - name: Audit
    description: Security audit account
    email: auditemalone@gmail.com
    organizationalUnit: Security

workloadAccounts: []
