mandatoryAccounts:
  - name: Management
    description: Management account
    email: scottemalone@gmail.com
    organizationalUnit: Root

  - name: LogArchive
    description: Central log archive account
    email: erikcmalone@gmail.com
    organizationalUnit: Security

  - name: Audit
    description: Security audit account
    email: mikeamalone@gmail.com
    organizationalUnit: Security

workloadAccounts: []
