homeRegion: us-east-1

enabledRegions:
  - us-east-1

managementAccountAccessRole: AWSControlTowerExecution

# Global CloudWatch Logs retention in days configuration
cloudwatchLogRetentionInDays: 365

terminationProtection: true

controlTower:
  enable: true

# logging:
#   account: LogArchive


logging:
  # ... other logging configurations
  sessionManager:
    # Indicates whether sending Session Manager logs to S3 is enabled
    # When enabled, logs are sent to the Central logs bucket in the Log Archive account
    sendToS3: true
    # Indicates whether sending Session Manager logs to CloudWatch Logs is enabled
    sendToCloudWatchLogs: true
    # List of AWS Account names to be excluded from this configuration
    excludeAccounts:
      - "Management"
    # List of AWS Region names to be excluded from this configuration
    excludeRegions: []
    # S3 Lifecycle rule for log storage (optional)
    lifecycleRules:
      - enabled: true
        expirationDays: 365 # Logs expire after 365 days
        transitionToInfrequentAccess: 30 # Transition to IA after 30 days
  account: LogArchive
  centralizedLoggingRegion: "us-east-1" # Region where the central logging bucket is deployed
  cloudtrail:
    enable: false
    organizationTrail: false
    # organizationTrailSettings:
    #   multiRegionTrail: true # Deploys a trail to all regions
    #   globalServiceEvents: true # Includes global service events (e.g., IAM, Route 53)
      # Optional settings:
      # managementEvents: true
      # lambdaDataEvents: true
      # s3DataEvents: false
      # includeS3BucketAccessLogs: false
      # enableLogFileValidation: true
      # enableAwsServiceCatalogProducts: true
      # enableCloudWatchLogs: true
      # apiCallRateInsight: false
