homeRegion: us-east-1

enabledRegions:
  - us-east-1

managementAccountAccessRole: AWSControlTowerExecution

# Global CloudWatch Logs retention in days configuration
cloudwatchLogRetentionInDays: 365

terminationProtection: true

controlTower:
  enable: true

logging:
  account: LogArchive
