accessAnalyzer:
  enable: false

guardduty:
  enable: false

cloudWatch: []ßsß
  # alarmSets:
  #   - alarms:
  #       - alarmDescription: 
  #         alarmName: 
  #         comparisonOperator: 
  #         evaluationPeriods: 
  #         metricName: 
  #         namespace: 
  #         period: 
  #         statistic: 
  #         threshold: 
  #         treatMissingData: 
  #     deploymentTargets:
        
  # metricSets:
  #   - metrics:
  #       - filterName: 
  #         filterPattern: 
  #         logGroupName: 
  #         metricName: 
  #         metricNamespace: 
  #         metricValue: 

iamPasswordPolicy:


centralSecurityServices:
  # The account that will be the delegated administrator for security services
  delegatedAdminAccount: "Audit"
  
  # Configuration for Amazon GuardDuty
  guardduty:
    enable: false
    # Optionally enable GuardDuty in all regions or specify deployment targets
    enableInAllRegions: false 
    # Optionally specify the SNS topic for notifications
    snsTopicName: "Security"
    exportConfiguration:
    s3Protection:

  # Configuration for AWS Security Hub
  securityHub:
    enable: false
    regionAggregation: true # Aggregate findings to the home region
    snsTopicName: "Security"
    notificationLevel: HIGH
    # Define standards to enable (e.g., AWS Foundational Security Best Practices)
    standards:
      - name: "AWS Foundational Security Best Practices v1.0.0"
        deploymentTargets:
          organizationalUnits:
            - "Root"
          enable: false
        enable: false
        # Optionally disable specific controls
        # controlsToDisable:
        #   - "ControlId1"
  
  # Configuration for Amazon Macie
  macie:
    enable: false
    # Optionally specify the frequency for publishing policy findings
    findingPublishingFrequency: "FIFTEEN_MINUTES"
    publishSensitiveDataFindings:

  # Configuration for AWS Audit Manager
  auditManager:
    enable: false
    # Optionally specify the SNS topic for notifications
    snsTopicName: "Security"
    defaultReportsConfiguration:

  # Configuration for Amazon S3 Public Access Block
  s3PublicAccessBlock:
    enable: false
    # Optionally exclude specific accounts if necessary
    excludeAccounts: []

  # Configuration for EBS Default Volume Encryption
  ebsDefaultVolumeEncryption:
    enable: false
    # The KMS key alias or ARN (LZA can create one per region if name specified)
    # kmsKey: "alias/aws/ebs" 
    excludeRegions: []

  # Configuration for AWS Systems Manager (SSM) Automation documents
  ssmAutomation:
    # Example to create an SSM document named "SSM-ELB-Enable-Logging"
    # and share with the Root organizational unit
    # SSM documents must be placed in the config repo
    documents:
      - name: "SSM-ELB-Enable-Logging"
        description: "Enable ELB logging"
        target:
          organizationalUnits:
            - "Root"





# securityHub:
#   enable: false
#   logging:
#     cloudWatch:
#       enable: false # Enables logging to CloudWatch
#       logGroupName: "/aws/security-hub/events" # The specific log group name
#       # logLevel: MEDIUM # An example of an optional property

macie:
  enable: false

ebsDefaultVolumeEncryption:
  enable: true
  excludeRegions: []

s3PublicAccessBlock:
  enable: true

scps: []

awsConfig:
  enableConfigurationRecorder: false
