centralSecurityServices:
  delegatedAdminAccount: Audit

accessAnalyzer:
  enable: false

guardduty:
  enable: false

enableCloudWatchLogs:
  enable: false

securityHub:
  enable: false
  logging:
    cloudWatch:
      enable: false # Enables logging to CloudWatch
      logGroupName: "/aws/security-hub/events" # The specific log group name
      # logLevel: MEDIUM # An example of an optional property

macie:
  enable: false

ebsDefaultVolumeEncryption:
  enable: true
  excludeRegions: []

s3PublicAccessBlock:
  enable: true

scps: []

awsConfig:
  enableConfigurationRecorder: false
