centralSecurityServices:
  delegatedAdminAccount: Audit

accessAnalyzer:
  enable: false

guardduty:
  enable: false

cloudWatch:
  # alarmSets:
  #   - alarms:
  #       - alarmDescription: 
  #         alarmName: 
  #         comparisonOperator: 
  #         evaluationPeriods: 
  #         metricName: 
  #         namespace: 
  #         period: 
  #         statistic: 
  #         threshold: 
  #         treatMissingData: 
  #     deploymentTargets:
        
  # metricSets:
  #   - metrics:
  #       - filterName: 
  #         filterPattern: 
  #         logGroupName: 
  #         metricName: 
  #         metricNamespace: 
  #         metricValue: 

iamPasswordPolicy:
  # allowUsersToChangePassword: true
  # hardExpiry: false
  # requireUppercaseCharacters: true
  # requireLowercaseCharacters: true
  # requireSymbols: true
  # requireNumbers: true


centralSecurityServices:
  delegatedAdminAccount: Audit # Or another account name
  securityHub:
    enabled: false
    enableFoundationalSecurityBestPractices: false
  guardDuty:
    enabled: false
    enableS3Protection: false
    enableEksProtection: false


# securityHub:
#   enable: false
#   logging:
#     cloudWatch:
#       enable: false # Enables logging to CloudWatch
#       logGroupName: "/aws/security-hub/events" # The specific log group name
#       # logLevel: MEDIUM # An example of an optional property

macie:
  enable: false

ebsDefaultVolumeEncryption:
  enable: true
  excludeRegions: []

s3PublicAccessBlock:
  enable: true

scps: []

awsConfig:
  enableConfigurationRecorder: false
